Repository ti-community-infra/prow, pull requests merged in 2025-05, with the labels that each got.

#8 fix(pkg/plugins/approve): minimize suggested approvers
  pkg/plugins/approve/approvers/owners.go
Labels: size/S

#9 feat(pkg/trigger): support approve GitHub action run with /test all
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/fakegithub/fakegithub.go
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/trigger.go
Labels: do-not-merge/hold, size/L

#10 feat(trigger): enhance comment handling to trigger GitHub Actions
  pkg/plugins/trigger/generic-comment.go
Labels: size/XS
